version: 2.1
orbs:
  flake8: arrai/flake8@5.0.0
workflows:
  version: 2
  test:
    jobs:
    - build-3.7
    - build-3.6
    - build-2.7

jobs:
  build-3.7: &test-template
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: deps2-{{ .Environment.CIRCLE_JOB}}-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            if [ "${CIRCLE_JOB}" == "build-2.7" ]; then
                virtualenv env
            else
                python3 -m venv env
            fi
            virtualenv --always-copy env
            . env/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps2-{{ .Environment.CIRCLE_JOB}}-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "env"
      - django_test:
          name: Running tests
          command: |
            . env/bin/activate
            python manage.py test
      - 
      - store_artifacts:
          path: test-reports/
          destination: python_app
  build-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6-jessie
  build-2.7:
    <<: *test-template
    docker:
      - image: circleci/python:2.7-jessie
